name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Railway CLI
        run: npm install -g railway
      - name: Set Railway Variables
        run: |
          railway variables set NOTION_API_KEY=${{ secrets.NOTION_API_KEY }}
          railway variables set NOTION_DATABASE_ID=${{ secrets.NOTION_DATABASE_ID }}
          railway variables set NOTION_CUSTOMER_DATABASE_ID=${{ secrets.NOTION_CUSTOMER_DATABASE_ID }}
          railway variables set NOTION_PRODUCT_DATABASE_ID=${{ secrets.NOTION_PRODUCT_DATABASE_ID }}
          railway variables set VITE_LIFF_ID=${{ secrets.VITE_LIFF_ID }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      - name: Deploy to Railway
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}